# Generated by Django 4.1.5 on 2023-01-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('priority', models.SmallIntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=3)),
                ('is_done', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('creates_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
